l_french:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 group_armor_title: "Bataillons blindés"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RImpossible de supprimer ce modèle car $AMOUNT|H$ divisions sont actuellement en train de passer à un nouveau modèle (en attente du matériel correspondant au nouveau modèle).§!"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Pour être affecté à un groupe, au moins un ordre sur le théâtre d'opérations doit être donné au déploiement."

#fixed missing article
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GCliquer§! pour définir le lieu de déploiement.\n§GClic droit§! pour réinitialiser le lieu.\n§YIl s'agit d'un modèle colonial, qui ne peut être déployé que dans le pays d'origine.§!"
